//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.31 at 10:37:07 AM CEST 
//


package org.datacleaner.components.dowjones.xml;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;sequence>
 *           &lt;element ref="{}PublicFigure" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element ref="{}SpecialEntity" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;/sequence>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "publicFigure",
        "specialEntity"
})
@XmlRootElement(name = "Associations")
public class Associations {

    @XmlElement(name = "PublicFigure")
    protected List<PublicFigure> publicFigure;
    @XmlElement(name = "SpecialEntity")
    protected List<SpecialEntity> specialEntity;

    /**
     * Gets the value of the publicFigure property.
     * <p/>
     * <p/>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the publicFigure property.
     * <p/>
     * <p/>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPublicFigure().add(newItem);
     * </pre>
     * <p/>
     * <p/>
     * <p/>
     * Objects of the following type(s) are allowed in the list
     * {@link PublicFigure }
     */
    public List<PublicFigure> getPublicFigure() {
        if (publicFigure == null) {
            publicFigure = new ArrayList<PublicFigure>();
        }
        return this.publicFigure;
    }

    /**
     * Gets the value of the specialEntity property.
     * <p/>
     * <p/>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the specialEntity property.
     * <p/>
     * <p/>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSpecialEntity().add(newItem);
     * </pre>
     * <p/>
     * <p/>
     * <p/>
     * Objects of the following type(s) are allowed in the list
     * {@link SpecialEntity }
     */
    public List<SpecialEntity> getSpecialEntity() {
        if (specialEntity == null) {
            specialEntity = new ArrayList<SpecialEntity>();
        }
        return this.specialEntity;
    }

}
