//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.31 at 10:37:07 AM CEST 
//


package org.datacleaner.components.dowjones.xml;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}CountryValue" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="CountryType" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "countryValue"
})
@XmlRootElement(name = "Country")
public class Country {

    @XmlElement(name = "CountryValue", required = true)
    protected List<CountryValue> countryValue;
    @XmlAttribute(name = "CountryType", required = true)
    protected String countryType;

    /**
     * Gets the value of the countryValue property.
     * <p/>
     * <p/>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the countryValue property.
     * <p/>
     * <p/>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCountryValue().add(newItem);
     * </pre>
     * <p/>
     * <p/>
     * <p/>
     * Objects of the following type(s) are allowed in the list
     * {@link CountryValue }
     */
    public List<CountryValue> getCountryValue() {
        if (countryValue == null) {
            countryValue = new ArrayList<CountryValue>();
        }
        return this.countryValue;
    }

    /**
     * Gets the value of the countryType property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getCountryType() {
        return countryType;
    }

    /**
     * Sets the value of the countryType property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setCountryType(String value) {
        this.countryType = value;
    }

}
