//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.31 at 10:37:07 AM CEST 
//


package org.datacleaner.components.dowjones.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="Day" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Month" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Year" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Dnotes" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "DateValue")
public class DateValue {

    @XmlAttribute(name = "Day")
    protected String day;
    @XmlAttribute(name = "Month")
    protected String month;
    @XmlAttribute(name = "Year")
    protected String year;
    @XmlAttribute(name = "Dnotes")
    protected String dnotes;

    /**
     * Gets the value of the day property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getDay() {
        return day;
    }

    /**
     * Sets the value of the day property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setDay(String value) {
        this.day = value;
    }

    /**
     * Gets the value of the month property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getMonth() {
        return month;
    }

    /**
     * Sets the value of the month property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setMonth(String value) {
        this.month = value;
    }

    /**
     * Gets the value of the year property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getYear() {
        return year;
    }

    /**
     * Sets the value of the year property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setYear(String value) {
        this.year = value;
    }

    /**
     * Gets the value of the dnotes property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getDnotes() {
        return dnotes;
    }

    /**
     * Sets the value of the dnotes property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setDnotes(String value) {
        this.dnotes = value;
    }

}
