//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.31 at 10:37:07 AM CEST 
//


package org.datacleaner.components.dowjones.xml;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType>
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *       &lt;attribute name="Description2Id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Description1Id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "value"
})
@XmlRootElement(name = "Description2Name")
public class Description2Name {

    @XmlValue
    protected String value;
    @XmlAttribute(name = "Description2Id", required = true)
    protected String description2Id;
    @XmlAttribute(name = "Description1Id", required = true)
    protected String description1Id;

    /**
     * Gets the value of the value property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the description2Id property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getDescription2Id() {
        return description2Id;
    }

    /**
     * Sets the value of the description2Id property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setDescription2Id(String value) {
        this.description2Id = value;
    }

    /**
     * Gets the value of the description1Id property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getDescription1Id() {
        return description1Id;
    }

    /**
     * Sets the value of the description1Id property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setDescription1Id(String value) {
        this.description1Id = value;
    }

}
