//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.31 at 10:37:07 AM CEST 
//


package org.datacleaner.components.dowjones.xml;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}ActiveStatus" minOccurs="0"/>
 *         &lt;element ref="{}NameDetails" minOccurs="0"/>
 *         &lt;element ref="{}Descriptions" minOccurs="0"/>
 *         &lt;element ref="{}DateDetails" minOccurs="0"/>
 *         &lt;element ref="{}SanctionsReferences" minOccurs="0"/>
 *         &lt;element ref="{}CompanyDetails" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}VesselDetails" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}CountryDetails" minOccurs="0"/>
 *         &lt;element ref="{}IDNumberTypes" minOccurs="0"/>
 *         &lt;element ref="{}ProfileNotes" minOccurs="0"/>
 *         &lt;element ref="{}SourceDescription" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="action" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *             &lt;enumeration value="del"/>
 *             &lt;enumeration value="chg"/>
 *             &lt;enumeration value="add"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="date" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "activeStatus",
        "nameDetails",
        "descriptions",
        "dateDetails",
        "sanctionsReferences",
        "companyDetails",
        "vesselDetails",
        "countryDetails",
        "idNumberTypes",
        "profileNotes",
        "sourceDescription"
})
@XmlRootElement(name = "Entity")
public class Entity {

    @XmlElement(name = "ActiveStatus")
    protected String activeStatus;
    @XmlElement(name = "NameDetails")
    protected NameDetails nameDetails;
    @XmlElement(name = "Descriptions")
    protected Descriptions descriptions;
    @XmlElement(name = "DateDetails")
    protected DateDetails dateDetails;
    @XmlElement(name = "SanctionsReferences")
    protected SanctionsReferences sanctionsReferences;
    @XmlElement(name = "CompanyDetails")
    protected List<CompanyDetails> companyDetails;
    @XmlElement(name = "VesselDetails")
    protected List<VesselDetails> vesselDetails;
    @XmlElement(name = "CountryDetails")
    protected CountryDetails countryDetails;
    @XmlElement(name = "IDNumberTypes")
    protected IDNumberTypes idNumberTypes;
    @XmlElement(name = "ProfileNotes")
    protected String profileNotes;
    @XmlElement(name = "SourceDescription")
    protected SourceDescription sourceDescription;
    @XmlAttribute(name = "id", required = true)
    protected String id;
    @XmlAttribute(name = "action", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String action;
    @XmlAttribute(name = "date", required = true)
    protected String date;

    /**
     * Gets the value of the activeStatus property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getActiveStatus() {
        return activeStatus;
    }

    /**
     * Sets the value of the activeStatus property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setActiveStatus(String value) {
        this.activeStatus = value;
    }

    /**
     * Gets the value of the nameDetails property.
     *
     * @return possible object is
     * {@link NameDetails }
     */
    public NameDetails getNameDetails() {
        return nameDetails;
    }

    /**
     * Sets the value of the nameDetails property.
     *
     * @param value allowed object is
     *              {@link NameDetails }
     */
    public void setNameDetails(NameDetails value) {
        this.nameDetails = value;
    }

    /**
     * Gets the value of the descriptions property.
     *
     * @return possible object is
     * {@link Descriptions }
     */
    public Descriptions getDescriptions() {
        return descriptions;
    }

    /**
     * Sets the value of the descriptions property.
     *
     * @param value allowed object is
     *              {@link Descriptions }
     */
    public void setDescriptions(Descriptions value) {
        this.descriptions = value;
    }

    /**
     * Gets the value of the dateDetails property.
     *
     * @return possible object is
     * {@link DateDetails }
     */
    public DateDetails getDateDetails() {
        return dateDetails;
    }

    /**
     * Sets the value of the dateDetails property.
     *
     * @param value allowed object is
     *              {@link DateDetails }
     */
    public void setDateDetails(DateDetails value) {
        this.dateDetails = value;
    }

    /**
     * Gets the value of the sanctionsReferences property.
     *
     * @return possible object is
     * {@link SanctionsReferences }
     */
    public SanctionsReferences getSanctionsReferences() {
        return sanctionsReferences;
    }

    /**
     * Sets the value of the sanctionsReferences property.
     *
     * @param value allowed object is
     *              {@link SanctionsReferences }
     */
    public void setSanctionsReferences(SanctionsReferences value) {
        this.sanctionsReferences = value;
    }

    /**
     * Gets the value of the companyDetails property.
     * <p/>
     * <p/>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the companyDetails property.
     * <p/>
     * <p/>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCompanyDetails().add(newItem);
     * </pre>
     * <p/>
     * <p/>
     * <p/>
     * Objects of the following type(s) are allowed in the list
     * {@link CompanyDetails }
     */
    public List<CompanyDetails> getCompanyDetails() {
        if (companyDetails == null) {
            companyDetails = new ArrayList<CompanyDetails>();
        }
        return this.companyDetails;
    }

    /**
     * Gets the value of the vesselDetails property.
     * <p/>
     * <p/>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the vesselDetails property.
     * <p/>
     * <p/>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getVesselDetails().add(newItem);
     * </pre>
     * <p/>
     * <p/>
     * <p/>
     * Objects of the following type(s) are allowed in the list
     * {@link VesselDetails }
     */
    public List<VesselDetails> getVesselDetails() {
        if (vesselDetails == null) {
            vesselDetails = new ArrayList<VesselDetails>();
        }
        return this.vesselDetails;
    }

    /**
     * Gets the value of the countryDetails property.
     *
     * @return possible object is
     * {@link CountryDetails }
     */
    public CountryDetails getCountryDetails() {
        return countryDetails;
    }

    /**
     * Sets the value of the countryDetails property.
     *
     * @param value allowed object is
     *              {@link CountryDetails }
     */
    public void setCountryDetails(CountryDetails value) {
        this.countryDetails = value;
    }

    /**
     * Gets the value of the idNumberTypes property.
     *
     * @return possible object is
     * {@link IDNumberTypes }
     */
    public IDNumberTypes getIDNumberTypes() {
        return idNumberTypes;
    }

    /**
     * Sets the value of the idNumberTypes property.
     *
     * @param value allowed object is
     *              {@link IDNumberTypes }
     */
    public void setIDNumberTypes(IDNumberTypes value) {
        this.idNumberTypes = value;
    }

    /**
     * Gets the value of the profileNotes property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getProfileNotes() {
        return profileNotes;
    }

    /**
     * Sets the value of the profileNotes property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setProfileNotes(String value) {
        this.profileNotes = value;
    }

    /**
     * Gets the value of the sourceDescription property.
     *
     * @return possible object is
     * {@link SourceDescription }
     */
    public SourceDescription getSourceDescription() {
        return sourceDescription;
    }

    /**
     * Sets the value of the sourceDescription property.
     *
     * @param value allowed object is
     *              {@link SourceDescription }
     */
    public void setSourceDescription(SourceDescription value) {
        this.sourceDescription = value;
    }

    /**
     * Gets the value of the id property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the action property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getAction() {
        return action;
    }

    /**
     * Sets the value of the action property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setAction(String value) {
        this.action = value;
    }

    /**
     * Gets the value of the date property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getDate() {
        return date;
    }

    /**
     * Sets the value of the date property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setDate(String value) {
        this.date = value;
    }

}
