//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.31 at 10:37:07 AM CEST 
//


package org.datacleaner.components.dowjones.xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}IDValue" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="IDType" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "idValue"
})
@XmlRootElement(name = "ID")
public class ID {

    @XmlElement(name = "IDValue", required = true)
    protected List<IDValue> idValue;
    @XmlAttribute(name = "IDType", required = true)
    protected String idType;

    /**
     * Gets the value of the idValue property.
     * <p>
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the idValue property.
     * <p>
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIDValue().add(newItem);
     * </pre>
     * <p>
     * <p>
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IDValue }
     */
    public List<IDValue> getIDValue() {
        if (idValue == null) {
            idValue = new ArrayList<IDValue>();
        }
        return this.idValue;
    }

    /**
     * Gets the value of the idType property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getIDType() {
        return idType;
    }

    /**
     * Sets the value of the idType property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setIDType(String value) {
        this.idType = value;
    }

}
