//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.31 at 10:37:07 AM CEST 
//


package org.datacleaner.components.dowjones.xml;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the org.datacleaner.components.dowjones.xml package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _TitleHonorific_QNAME = new QName("", "TitleHonorific");
    private final static QName _SingleStringName_QNAME = new QName("", "SingleStringName");
    private final static QName _VesselType_QNAME = new QName("", "VesselType");
    private final static QName _EntityName_QNAME = new QName("", "EntityName");
    private final static QName _VesselTonnage_QNAME = new QName("", "VesselTonnage");
    private final static QName _FirstName_QNAME = new QName("", "FirstName");
    private final static QName _AddressLine_QNAME = new QName("", "AddressLine");
    private final static QName _Deceased_QNAME = new QName("", "Deceased");
    private final static QName _AddressCountry_QNAME = new QName("", "AddressCountry");
    private final static QName _Gender_QNAME = new QName("", "Gender");
    private final static QName _MiddleName_QNAME = new QName("", "MiddleName");
    private final static QName _VesselGRT_QNAME = new QName("", "VesselGRT");
    private final static QName _URL_QNAME = new QName("", "URL");
    private final static QName _VesselFlag_QNAME = new QName("", "VesselFlag");
    private final static QName _ActiveStatus_QNAME = new QName("", "ActiveStatus");
    private final static QName _OriginalScriptName_QNAME = new QName("", "OriginalScriptName");
    private final static QName _Suffix_QNAME = new QName("", "Suffix");
    private final static QName _VesselCallSign_QNAME = new QName("", "VesselCallSign");
    private final static QName _ProfileNotes_QNAME = new QName("", "ProfileNotes");
    private final static QName _AddressCity_QNAME = new QName("", "AddressCity");
    private final static QName _VesselOwner_QNAME = new QName("", "VesselOwner");
    private final static QName _Surname_QNAME = new QName("", "Surname");
    private final static QName _MaidenName_QNAME = new QName("", "MaidenName");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.datacleaner.components.dowjones.xml
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SpecialEntity }
     */
    public SpecialEntity createSpecialEntity() {
        return new SpecialEntity();
    }

    /**
     * Create an instance of {@link Associate }
     */
    public Associate createAssociate() {
        return new Associate();
    }

    /**
     * Create an instance of {@link Entity }
     */
    public Entity createEntity() {
        return new Entity();
    }

    /**
     * Create an instance of {@link NameDetails }
     */
    public NameDetails createNameDetails() {
        return new NameDetails();
    }

    /**
     * Create an instance of {@link Name }
     */
    public Name createName() {
        return new Name();
    }

    /**
     * Create an instance of {@link NameValue }
     */
    public NameValue createNameValue() {
        return new NameValue();
    }

    /**
     * Create an instance of {@link Descriptions }
     */
    public Descriptions createDescriptions() {
        return new Descriptions();
    }

    /**
     * Create an instance of {@link Description }
     */
    public Description createDescription() {
        return new Description();
    }

    /**
     * Create an instance of {@link DateDetails }
     */
    public DateDetails createDateDetails() {
        return new DateDetails();
    }

    /**
     * Create an instance of {@link Date }
     */
    public Date createDate() {
        return new Date();
    }

    /**
     * Create an instance of {@link DateValue }
     */
    public DateValue createDateValue() {
        return new DateValue();
    }

    /**
     * Create an instance of {@link SanctionsReferences }
     */
    public SanctionsReferences createSanctionsReferences() {
        return new SanctionsReferences();
    }

    /**
     * Create an instance of {@link Reference }
     */
    public Reference createReference() {
        return new Reference();
    }

    /**
     * Create an instance of {@link CompanyDetails }
     */
    public CompanyDetails createCompanyDetails() {
        return new CompanyDetails();
    }

    /**
     * Create an instance of {@link VesselDetails }
     */
    public VesselDetails createVesselDetails() {
        return new VesselDetails();
    }

    /**
     * Create an instance of {@link CountryDetails }
     */
    public CountryDetails createCountryDetails() {
        return new CountryDetails();
    }

    /**
     * Create an instance of {@link Country }
     */
    public Country createCountry() {
        return new Country();
    }

    /**
     * Create an instance of {@link CountryValue }
     */
    public CountryValue createCountryValue() {
        return new CountryValue();
    }

    /**
     * Create an instance of {@link IDNumberTypes }
     */
    public IDNumberTypes createIDNumberTypes() {
        return new IDNumberTypes();
    }

    /**
     * Create an instance of {@link ID }
     */
    public ID createID() {
        return new ID();
    }

    /**
     * Create an instance of {@link IDValue }
     */
    public IDValue createIDValue() {
        return new IDValue();
    }

    /**
     * Create an instance of {@link SourceDescription }
     */
    public SourceDescription createSourceDescription() {
        return new SourceDescription();
    }

    /**
     * Create an instance of {@link Source }
     */
    public Source createSource() {
        return new Source();
    }

    /**
     * Create an instance of {@link Description3Name }
     */
    public Description3Name createDescription3Name() {
        return new Description3Name();
    }

    /**
     * Create an instance of {@link BirthPlace }
     */
    public BirthPlace createBirthPlace() {
        return new BirthPlace();
    }

    /**
     * Create an instance of {@link Place }
     */
    public Place createPlace() {
        return new Place();
    }

    /**
     * Create an instance of {@link Address }
     */
    public Address createAddress() {
        return new Address();
    }

    /**
     * Create an instance of {@link RoleType }
     */
    public RoleType createRoleType() {
        return new RoleType();
    }

    /**
     * Create an instance of {@link PFA }
     */
    public PFA createPFA() {
        return new PFA();
    }

    /**
     * Create an instance of {@link CountryList }
     */
    public CountryList createCountryList() {
        return new CountryList();
    }

    /**
     * Create an instance of {@link CountryName }
     */
    public CountryName createCountryName() {
        return new CountryName();
    }

    /**
     * Create an instance of {@link OccupationList }
     */
    public OccupationList createOccupationList() {
        return new OccupationList();
    }

    /**
     * Create an instance of {@link Occupation }
     */
    public Occupation createOccupation() {
        return new Occupation();
    }

    /**
     * Create an instance of {@link RelationshipList }
     */
    public RelationshipList createRelationshipList() {
        return new RelationshipList();
    }

    /**
     * Create an instance of {@link Relationship }
     */
    public Relationship createRelationship() {
        return new Relationship();
    }

    /**
     * Create an instance of {@link SanctionsReferencesList }
     */
    public SanctionsReferencesList createSanctionsReferencesList() {
        return new SanctionsReferencesList();
    }

    /**
     * Create an instance of {@link ReferenceName }
     */
    public ReferenceName createReferenceName() {
        return new ReferenceName();
    }

    /**
     * Create an instance of {@link Description1List }
     */
    public Description1List createDescription1List() {
        return new Description1List();
    }

    /**
     * Create an instance of {@link Description1Name }
     */
    public Description1Name createDescription1Name() {
        return new Description1Name();
    }

    /**
     * Create an instance of {@link Description2List }
     */
    public Description2List createDescription2List() {
        return new Description2List();
    }

    /**
     * Create an instance of {@link Description2Name }
     */
    public Description2Name createDescription2Name() {
        return new Description2Name();
    }

    /**
     * Create an instance of {@link Description3List }
     */
    public Description3List createDescription3List() {
        return new Description3List();
    }

    /**
     * Create an instance of {@link DateTypeList }
     */
    public DateTypeList createDateTypeList() {
        return new DateTypeList();
    }

    /**
     * Create an instance of {@link DateType }
     */
    public DateType createDateType() {
        return new DateType();
    }

    /**
     * Create an instance of {@link NameTypeList }
     */
    public NameTypeList createNameTypeList() {
        return new NameTypeList();
    }

    /**
     * Create an instance of {@link NameType }
     */
    public NameType createNameType() {
        return new NameType();
    }

    /**
     * Create an instance of {@link RoleTypeList }
     */
    public RoleTypeList createRoleTypeList() {
        return new RoleTypeList();
    }

    /**
     * Create an instance of {@link Records }
     */
    public Records createRecords() {
        return new Records();
    }

    /**
     * Create an instance of {@link Person }
     */
    public Person createPerson() {
        return new Person();
    }

    /**
     * Create an instance of {@link RoleDetail }
     */
    public RoleDetail createRoleDetail() {
        return new RoleDetail();
    }

    /**
     * Create an instance of {@link Roles }
     */
    public Roles createRoles() {
        return new Roles();
    }

    /**
     * Create an instance of {@link OccTitle }
     */
    public OccTitle createOccTitle() {
        return new OccTitle();
    }

    /**
     * Create an instance of {@link Images }
     */
    public Images createImages() {
        return new Images();
    }

    /**
     * Create an instance of {@link Image }
     */
    public Image createImage() {
        return new Image();
    }

    /**
     * Create an instance of {@link Associations }
     */
    public Associations createAssociations() {
        return new Associations();
    }

    /**
     * Create an instance of {@link PublicFigure }
     */
    public PublicFigure createPublicFigure() {
        return new PublicFigure();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "TitleHonorific")
    public JAXBElement<String> createTitleHonorific(String value) {
        return new JAXBElement<String>(_TitleHonorific_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "SingleStringName")
    public JAXBElement<String> createSingleStringName(String value) {
        return new JAXBElement<String>(_SingleStringName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "VesselType")
    public JAXBElement<String> createVesselType(String value) {
        return new JAXBElement<String>(_VesselType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "EntityName")
    public JAXBElement<String> createEntityName(String value) {
        return new JAXBElement<String>(_EntityName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "VesselTonnage")
    public JAXBElement<String> createVesselTonnage(String value) {
        return new JAXBElement<String>(_VesselTonnage_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "FirstName")
    public JAXBElement<String> createFirstName(String value) {
        return new JAXBElement<String>(_FirstName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "AddressLine")
    public JAXBElement<String> createAddressLine(String value) {
        return new JAXBElement<String>(_AddressLine_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "Deceased")
    public JAXBElement<String> createDeceased(String value) {
        return new JAXBElement<String>(_Deceased_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "AddressCountry")
    public JAXBElement<String> createAddressCountry(String value) {
        return new JAXBElement<String>(_AddressCountry_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "Gender")
    public JAXBElement<String> createGender(String value) {
        return new JAXBElement<String>(_Gender_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "MiddleName")
    public JAXBElement<String> createMiddleName(String value) {
        return new JAXBElement<String>(_MiddleName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "VesselGRT")
    public JAXBElement<String> createVesselGRT(String value) {
        return new JAXBElement<String>(_VesselGRT_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "URL")
    public JAXBElement<String> createURL(String value) {
        return new JAXBElement<String>(_URL_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "VesselFlag")
    public JAXBElement<String> createVesselFlag(String value) {
        return new JAXBElement<String>(_VesselFlag_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "ActiveStatus")
    public JAXBElement<String> createActiveStatus(String value) {
        return new JAXBElement<String>(_ActiveStatus_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "OriginalScriptName")
    public JAXBElement<String> createOriginalScriptName(String value) {
        return new JAXBElement<String>(_OriginalScriptName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "Suffix")
    public JAXBElement<String> createSuffix(String value) {
        return new JAXBElement<String>(_Suffix_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "VesselCallSign")
    public JAXBElement<String> createVesselCallSign(String value) {
        return new JAXBElement<String>(_VesselCallSign_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "ProfileNotes")
    public JAXBElement<String> createProfileNotes(String value) {
        return new JAXBElement<String>(_ProfileNotes_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "AddressCity")
    public JAXBElement<String> createAddressCity(String value) {
        return new JAXBElement<String>(_AddressCity_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "VesselOwner")
    public JAXBElement<String> createVesselOwner(String value) {
        return new JAXBElement<String>(_VesselOwner_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "Surname")
    public JAXBElement<String> createSurname(String value) {
        return new JAXBElement<String>(_Surname_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "MaidenName")
    public JAXBElement<String> createMaidenName(String value) {
        return new JAXBElement<String>(_MaidenName_QNAME, String.class, null, value);
    }

}
