//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.31 at 10:37:07 AM CEST 
//


package org.datacleaner.components.dowjones.xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}Gender" minOccurs="0"/>
 *         &lt;element ref="{}ActiveStatus" minOccurs="0"/>
 *         &lt;element ref="{}Deceased" minOccurs="0"/>
 *         &lt;element ref="{}NameDetails" minOccurs="0"/>
 *         &lt;element ref="{}Descriptions" minOccurs="0"/>
 *         &lt;element ref="{}RoleDetail" minOccurs="0"/>
 *         &lt;element ref="{}DateDetails" minOccurs="0"/>
 *         &lt;element ref="{}BirthPlace" minOccurs="0"/>
 *         &lt;element ref="{}SanctionsReferences" minOccurs="0"/>
 *         &lt;element ref="{}Address" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}CountryDetails" minOccurs="0"/>
 *         &lt;element ref="{}IDNumberTypes" minOccurs="0"/>
 *         &lt;element ref="{}ProfileNotes" minOccurs="0"/>
 *         &lt;element ref="{}SourceDescription" minOccurs="0"/>
 *         &lt;element ref="{}Images" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="action" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *             &lt;enumeration value="del"/>
 *             &lt;enumeration value="chg"/>
 *             &lt;enumeration value="add"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="date" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "gender",
        "activeStatus",
        "deceased",
        "nameDetails",
        "descriptions",
        "roleDetail",
        "dateDetails",
        "birthPlace",
        "sanctionsReferences",
        "address",
        "countryDetails",
        "idNumberTypes",
        "profileNotes",
        "sourceDescription",
        "images"
})
@XmlRootElement(name = "Person")
public class Person {

    @XmlElement(name = "Gender")
    protected String gender;
    @XmlElement(name = "ActiveStatus")
    protected String activeStatus;
    @XmlElement(name = "Deceased")
    protected String deceased;
    @XmlElement(name = "NameDetails")
    protected NameDetails nameDetails;
    @XmlElement(name = "Descriptions")
    protected Descriptions descriptions;
    @XmlElement(name = "RoleDetail")
    protected RoleDetail roleDetail;
    @XmlElement(name = "DateDetails")
    protected DateDetails dateDetails;
    @XmlElement(name = "BirthPlace")
    protected BirthPlace birthPlace;
    @XmlElement(name = "SanctionsReferences")
    protected SanctionsReferences sanctionsReferences;
    @XmlElement(name = "Address")
    protected List<Address> address;
    @XmlElement(name = "CountryDetails")
    protected CountryDetails countryDetails;
    @XmlElement(name = "IDNumberTypes")
    protected IDNumberTypes idNumberTypes;
    @XmlElement(name = "ProfileNotes")
    protected String profileNotes;
    @XmlElement(name = "SourceDescription")
    protected SourceDescription sourceDescription;
    @XmlElement(name = "Images")
    protected Images images;
    @XmlAttribute(name = "id", required = true)
    protected String id;
    @XmlAttribute(name = "action", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String action;
    @XmlAttribute(name = "date", required = true)
    protected String date;

    /**
     * Gets the value of the gender property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getGender() {
        return gender;
    }

    /**
     * Sets the value of the gender property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setGender(String value) {
        this.gender = value;
    }

    /**
     * Gets the value of the activeStatus property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getActiveStatus() {
        return activeStatus;
    }

    /**
     * Sets the value of the activeStatus property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setActiveStatus(String value) {
        this.activeStatus = value;
    }

    /**
     * Gets the value of the deceased property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getDeceased() {
        return deceased;
    }

    /**
     * Sets the value of the deceased property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setDeceased(String value) {
        this.deceased = value;
    }

    /**
     * Gets the value of the nameDetails property.
     *
     * @return possible object is
     * {@link NameDetails }
     */
    public NameDetails getNameDetails() {
        return nameDetails;
    }

    /**
     * Sets the value of the nameDetails property.
     *
     * @param value allowed object is
     *              {@link NameDetails }
     */
    public void setNameDetails(NameDetails value) {
        this.nameDetails = value;
    }

    /**
     * Gets the value of the descriptions property.
     *
     * @return possible object is
     * {@link Descriptions }
     */
    public Descriptions getDescriptions() {
        return descriptions;
    }

    /**
     * Sets the value of the descriptions property.
     *
     * @param value allowed object is
     *              {@link Descriptions }
     */
    public void setDescriptions(Descriptions value) {
        this.descriptions = value;
    }

    /**
     * Gets the value of the roleDetail property.
     *
     * @return possible object is
     * {@link RoleDetail }
     */
    public RoleDetail getRoleDetail() {
        return roleDetail;
    }

    /**
     * Sets the value of the roleDetail property.
     *
     * @param value allowed object is
     *              {@link RoleDetail }
     */
    public void setRoleDetail(RoleDetail value) {
        this.roleDetail = value;
    }

    /**
     * Gets the value of the dateDetails property.
     *
     * @return possible object is
     * {@link DateDetails }
     */
    public DateDetails getDateDetails() {
        return dateDetails;
    }

    /**
     * Sets the value of the dateDetails property.
     *
     * @param value allowed object is
     *              {@link DateDetails }
     */
    public void setDateDetails(DateDetails value) {
        this.dateDetails = value;
    }

    /**
     * Gets the value of the birthPlace property.
     *
     * @return possible object is
     * {@link BirthPlace }
     */
    public BirthPlace getBirthPlace() {
        return birthPlace;
    }

    /**
     * Sets the value of the birthPlace property.
     *
     * @param value allowed object is
     *              {@link BirthPlace }
     */
    public void setBirthPlace(BirthPlace value) {
        this.birthPlace = value;
    }

    /**
     * Gets the value of the sanctionsReferences property.
     *
     * @return possible object is
     * {@link SanctionsReferences }
     */
    public SanctionsReferences getSanctionsReferences() {
        return sanctionsReferences;
    }

    /**
     * Sets the value of the sanctionsReferences property.
     *
     * @param value allowed object is
     *              {@link SanctionsReferences }
     */
    public void setSanctionsReferences(SanctionsReferences value) {
        this.sanctionsReferences = value;
    }

    /**
     * Gets the value of the address property.
     * <p>
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the address property.
     * <p>
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAddress().add(newItem);
     * </pre>
     * <p>
     * <p>
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Address }
     */
    public List<Address> getAddress() {
        if (address == null) {
            address = new ArrayList<Address>();
        }
        return this.address;
    }

    /**
     * Gets the value of the countryDetails property.
     *
     * @return possible object is
     * {@link CountryDetails }
     */
    public CountryDetails getCountryDetails() {
        return countryDetails;
    }

    /**
     * Sets the value of the countryDetails property.
     *
     * @param value allowed object is
     *              {@link CountryDetails }
     */
    public void setCountryDetails(CountryDetails value) {
        this.countryDetails = value;
    }

    /**
     * Gets the value of the idNumberTypes property.
     *
     * @return possible object is
     * {@link IDNumberTypes }
     */
    public IDNumberTypes getIDNumberTypes() {
        return idNumberTypes;
    }

    /**
     * Sets the value of the idNumberTypes property.
     *
     * @param value allowed object is
     *              {@link IDNumberTypes }
     */
    public void setIDNumberTypes(IDNumberTypes value) {
        this.idNumberTypes = value;
    }

    /**
     * Gets the value of the profileNotes property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getProfileNotes() {
        return profileNotes;
    }

    /**
     * Sets the value of the profileNotes property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setProfileNotes(String value) {
        this.profileNotes = value;
    }

    /**
     * Gets the value of the sourceDescription property.
     *
     * @return possible object is
     * {@link SourceDescription }
     */
    public SourceDescription getSourceDescription() {
        return sourceDescription;
    }

    /**
     * Sets the value of the sourceDescription property.
     *
     * @param value allowed object is
     *              {@link SourceDescription }
     */
    public void setSourceDescription(SourceDescription value) {
        this.sourceDescription = value;
    }

    /**
     * Gets the value of the images property.
     *
     * @return possible object is
     * {@link Images }
     */
    public Images getImages() {
        return images;
    }

    /**
     * Sets the value of the images property.
     *
     * @param value allowed object is
     *              {@link Images }
     */
    public void setImages(Images value) {
        this.images = value;
    }

    /**
     * Gets the value of the id property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the action property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getAction() {
        return action;
    }

    /**
     * Sets the value of the action property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setAction(String value) {
        this.action = value;
    }

    /**
     * Gets the value of the date property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getDate() {
        return date;
    }

    /**
     * Sets the value of the date property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setDate(String value) {
        this.date = value;
    }

}
