//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.31 at 10:37:07 AM CEST 
//


package org.datacleaner.components.dowjones.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;sequence>
 *           &lt;element ref="{}CountryList"/>
 *           &lt;element ref="{}OccupationList"/>
 *           &lt;element ref="{}RelationshipList"/>
 *           &lt;element ref="{}SanctionsReferencesList"/>
 *           &lt;element ref="{}Description1List"/>
 *           &lt;element ref="{}Description2List"/>
 *           &lt;element ref="{}Description3List"/>
 *           &lt;element ref="{}DateTypeList"/>
 *           &lt;element ref="{}NameTypeList"/>
 *           &lt;element ref="{}RoleTypeList"/>
 *           &lt;element ref="{}Records"/>
 *           &lt;element ref="{}Associations"/>
 *         &lt;/sequence>
 *       &lt;/sequence>
 *       &lt;attribute name="date" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="type" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "countryList",
        "occupationList",
        "relationshipList",
        "sanctionsReferencesList",
        "description1List",
        "description2List",
        "description3List",
        "dateTypeList",
        "nameTypeList",
        "roleTypeList",
        "records",
        "associations"
})
@XmlRootElement(name = "PFA")
public class PFA {

    @XmlElement(name = "CountryList", required = true)
    protected CountryList countryList;
    @XmlElement(name = "OccupationList", required = true)
    protected OccupationList occupationList;
    @XmlElement(name = "RelationshipList", required = true)
    protected RelationshipList relationshipList;
    @XmlElement(name = "SanctionsReferencesList", required = true)
    protected SanctionsReferencesList sanctionsReferencesList;
    @XmlElement(name = "Description1List", required = true)
    protected Description1List description1List;
    @XmlElement(name = "Description2List", required = true)
    protected Description2List description2List;
    @XmlElement(name = "Description3List", required = true)
    protected Description3List description3List;
    @XmlElement(name = "DateTypeList", required = true)
    protected DateTypeList dateTypeList;
    @XmlElement(name = "NameTypeList", required = true)
    protected NameTypeList nameTypeList;
    @XmlElement(name = "RoleTypeList", required = true)
    protected RoleTypeList roleTypeList;
    @XmlElement(name = "Records", required = true)
    protected Records records;
    @XmlElement(name = "Associations", required = true)
    protected Associations associations;
    @XmlAttribute(name = "date", required = true)
    protected String date;
    @XmlAttribute(name = "type", required = true)
    protected String type;

    /**
     * Gets the value of the countryList property.
     *
     * @return possible object is
     * {@link CountryList }
     */
    public CountryList getCountryList() {
        return countryList;
    }

    /**
     * Sets the value of the countryList property.
     *
     * @param value allowed object is
     *              {@link CountryList }
     */
    public void setCountryList(CountryList value) {
        this.countryList = value;
    }

    /**
     * Gets the value of the occupationList property.
     *
     * @return possible object is
     * {@link OccupationList }
     */
    public OccupationList getOccupationList() {
        return occupationList;
    }

    /**
     * Sets the value of the occupationList property.
     *
     * @param value allowed object is
     *              {@link OccupationList }
     */
    public void setOccupationList(OccupationList value) {
        this.occupationList = value;
    }

    /**
     * Gets the value of the relationshipList property.
     *
     * @return possible object is
     * {@link RelationshipList }
     */
    public RelationshipList getRelationshipList() {
        return relationshipList;
    }

    /**
     * Sets the value of the relationshipList property.
     *
     * @param value allowed object is
     *              {@link RelationshipList }
     */
    public void setRelationshipList(RelationshipList value) {
        this.relationshipList = value;
    }

    /**
     * Gets the value of the sanctionsReferencesList property.
     *
     * @return possible object is
     * {@link SanctionsReferencesList }
     */
    public SanctionsReferencesList getSanctionsReferencesList() {
        return sanctionsReferencesList;
    }

    /**
     * Sets the value of the sanctionsReferencesList property.
     *
     * @param value allowed object is
     *              {@link SanctionsReferencesList }
     */
    public void setSanctionsReferencesList(SanctionsReferencesList value) {
        this.sanctionsReferencesList = value;
    }

    /**
     * Gets the value of the description1List property.
     *
     * @return possible object is
     * {@link Description1List }
     */
    public Description1List getDescription1List() {
        return description1List;
    }

    /**
     * Sets the value of the description1List property.
     *
     * @param value allowed object is
     *              {@link Description1List }
     */
    public void setDescription1List(Description1List value) {
        this.description1List = value;
    }

    /**
     * Gets the value of the description2List property.
     *
     * @return possible object is
     * {@link Description2List }
     */
    public Description2List getDescription2List() {
        return description2List;
    }

    /**
     * Sets the value of the description2List property.
     *
     * @param value allowed object is
     *              {@link Description2List }
     */
    public void setDescription2List(Description2List value) {
        this.description2List = value;
    }

    /**
     * Gets the value of the description3List property.
     *
     * @return possible object is
     * {@link Description3List }
     */
    public Description3List getDescription3List() {
        return description3List;
    }

    /**
     * Sets the value of the description3List property.
     *
     * @param value allowed object is
     *              {@link Description3List }
     */
    public void setDescription3List(Description3List value) {
        this.description3List = value;
    }

    /**
     * Gets the value of the dateTypeList property.
     *
     * @return possible object is
     * {@link DateTypeList }
     */
    public DateTypeList getDateTypeList() {
        return dateTypeList;
    }

    /**
     * Sets the value of the dateTypeList property.
     *
     * @param value allowed object is
     *              {@link DateTypeList }
     */
    public void setDateTypeList(DateTypeList value) {
        this.dateTypeList = value;
    }

    /**
     * Gets the value of the nameTypeList property.
     *
     * @return possible object is
     * {@link NameTypeList }
     */
    public NameTypeList getNameTypeList() {
        return nameTypeList;
    }

    /**
     * Sets the value of the nameTypeList property.
     *
     * @param value allowed object is
     *              {@link NameTypeList }
     */
    public void setNameTypeList(NameTypeList value) {
        this.nameTypeList = value;
    }

    /**
     * Gets the value of the roleTypeList property.
     *
     * @return possible object is
     * {@link RoleTypeList }
     */
    public RoleTypeList getRoleTypeList() {
        return roleTypeList;
    }

    /**
     * Sets the value of the roleTypeList property.
     *
     * @param value allowed object is
     *              {@link RoleTypeList }
     */
    public void setRoleTypeList(RoleTypeList value) {
        this.roleTypeList = value;
    }

    /**
     * Gets the value of the records property.
     *
     * @return possible object is
     * {@link Records }
     */
    public Records getRecords() {
        return records;
    }

    /**
     * Sets the value of the records property.
     *
     * @param value allowed object is
     *              {@link Records }
     */
    public void setRecords(Records value) {
        this.records = value;
    }

    /**
     * Gets the value of the associations property.
     *
     * @return possible object is
     * {@link Associations }
     */
    public Associations getAssociations() {
        return associations;
    }

    /**
     * Sets the value of the associations property.
     *
     * @param value allowed object is
     *              {@link Associations }
     */
    public void setAssociations(Associations value) {
        this.associations = value;
    }

    /**
     * Gets the value of the date property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getDate() {
        return date;
    }

    /**
     * Sets the value of the date property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setDate(String value) {
        this.date = value;
    }

    /**
     * Gets the value of the type property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setType(String value) {
        this.type = value;
    }

}
