//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.31 at 10:37:07 AM CEST 
//


package org.datacleaner.components.dowjones.xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}OccTitle" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="RoleType" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "occTitle"
})
@XmlRootElement(name = "Roles")
public class Roles {

    @XmlElement(name = "OccTitle", required = true)
    protected List<OccTitle> occTitle;
    @XmlAttribute(name = "RoleType", required = true)
    protected String roleType;

    /**
     * Gets the value of the occTitle property.
     * <p>
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the occTitle property.
     * <p>
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOccTitle().add(newItem);
     * </pre>
     * <p>
     * <p>
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OccTitle }
     */
    public List<OccTitle> getOccTitle() {
        if (occTitle == null) {
            occTitle = new ArrayList<OccTitle>();
        }
        return this.occTitle;
    }

    /**
     * Gets the value of the roleType property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getRoleType() {
        return roleType;
    }

    /**
     * Sets the value of the roleType property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setRoleType(String value) {
        this.roleType = value;
    }

}
